apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: t7dyb3eia-python-gitops
  description: This is GitOps manifest for t7dyb3eia-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=t7dyb3eia-python
    backstage.io/kubernetes-id: t7dyb3eia-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: t7dyb3eia-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:t7dyb3eia-python
